version: '3'
services:
  db:
    image: mysql:latest
    container_name: ford_db_container
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ford_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
